# Generated by Django 5.0.3 on 2024-04-19 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_subject_studentmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='reportcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_o_report', models.DateField(auto_created=True)),
                ('Student_rank_12', models.IntegerField()),
                ('Student12', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentreportcard', to='app1.student')),
            ],
        ),
    ]
