# Generated by Django 5.0.3 on 2024-04-19 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_reportcard'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reportcard',
            unique_together={('Student_rank_12', 'date_o_report')},
        ),
    ]
